### ISSUE TITLE
local files missing?

### ISSUE THREAD

**Issue by zijin2** [rodrigo-pedro/gemma-function-calling#1]
Hi, rodrigo,
Just want to have a try of ‘usage’ instead of ‘finetune’, When run ```tokenizer = AutoTokenizer.from_pretrained("rodrigo-pedro/gemma-2b-function-calling", trust_remote_code=True)``` with all files already downloaded from https://huggingface.co/rodrigo-pedro/gemma-2b-function-calling/tree/main and put in the path, terminal still requires to connect internet due to “couldn't find in the cached files”. So are there any other files that need to be in the tree/main folder?

**Comment by rodrigo-pedro** [comment]
Hi @linsong8208. Thank you for reaching out and for your interest in the function calling model.

Regarding the issue you're experiencing, I believe it is happening because your Hugging Face account does not have access to the Gemma models. Google has made it so that you have to accept some terms and conditions before you can download their models. Since my model is a fine-tuned gemma-2b-it, you need to request access first.

You can do this by going to the gemma-2b-it [model page](https://huggingface.co/google/gemma-2b-it) and requesting access there. I can't recall if you get access immediately or if there's a small waiting period, but once you've been accepted you should also have access to all other variants of the Gemma model.

Once that's done, make sure you're also authenticated on HuggingFace on your machine. Please refer to this [guide](https://huggingface.co/docs/huggingface_hub/en/quick-start#authentication).

I apologize that this information is not in the readme. I'm updating it now.

Please reach out if you have managed to get it working or if you are still having the same problem.

**Comment by zijin2** [comment]
Hi, rodrigo,
Thanks for answering, but
1， i fully knew i need to accept terms in the authentication to access the model and already finished that process and downloaded official 2b-it folder to my local machine before i raised this issue, so actually i assume there should be no necessity to connect internet in this situation.
2, since 2b-it have been downloaded, when i run 
```model = AutoModelForCausalLM.from_pretrained("gemma-2b-it", trust_remote_code=True, device_map="auto")```, everything all fine.
3, But with https://huggingface.co/rodrigo-pedro/gemma-2b-function-calling/tree/main also downloaded to my local machine, when i run 
```model = AutoModelForCausalLM.from_pretrained("rodrigo-pedro/gemma-2b-function-calling", trust_remote_code=True, device_map="auto")```(of course path already adjusted), OSError of trying to connect internet reported. That is why i thought there should be some extra files in folder. 
4, Are files in https://huggingface.co/rodrigo-pedro/gemma-2b-function-calling/tree/main ALL for “usage”? or need to combine them with 2b-it?

**Comment by rodrigo-pedro** [comment]
I think I figured it out. Try running `pip install peft` first. 

The model was trained with qlora so the repo only contains the delta weights. To load these models, the hugging face documentation says you can simply use `AutoModelForCausalLM`, but what it doesn't say is that if you don't have the `peft` package installed you get an error.

**Comment by zijin2** [comment]
I had also pip installed everything mentioned in your finetune notebook, so it can not be the peft reason.
Actually there is a way you can partly see the problem i face (not exactly the same but similar), upload your function calling folder to kaggle, take this folder as dataset and take gemma2bit as model, run your usage code, it should report something like “/kaggle/input/path does not appear to have a file named config.json.”

**Comment by rodrigo-pedro** [comment]
I tried running the inference code on a fresh instance of Google Colab and on another machine of mine and both times it worked fine. 

Here is the [colab link](https://github.com/huggingface/trl/blob/v0.8.1/trl/trainer/sft_trainer.py#L377) project I tested on. Run the first two cells, add your HF token, and then run the last cell. Set the instance as GPU as well.

When I trained the model, I used [push_to_hub](https://github.com/huggingface/trl/blob/v0.8.1/trl/trainer/sft_trainer.py#L377) to save the model to HuggingFace, so no files should be missing.

I recommend not manually downloading the model files like you did in Kaggle. Instead just run the usage code, as it will download all the necessary files automatically.

**Comment by zijin2** [comment]
Now in a new kaggle notebook, https://www.kaggle.com/code/linsong/rodrigo-usage-without-input, set hftoken, set gpu, no downloaded model files, no datasets, just run usage code, still error.
Also try this notebook in googlecolab, still same error.

**Comment by rodrigo-pedro** [comment]
You have two issues in your code.

1. The peft package is not installed. You can check if it is installed by running a cell with the code `%pip show peft`. It should say `WARNING: Package(s) not found: peft`. Please add a cell with `%pip install peft`. You may need to restart the runtime after.

2. You forgot to use the HF access_token when calling `AutoModelForCausalLM.from_pretrained`. Please add a `token=access_token` argument to the function. It's easy to forget, so I recommend instead using:

```python
from huggingface_hub import login
login()
```

Here is the same [kaggle notebook](https://www.kaggle.com/code/rodrigopedro/rodrigo-usage-without-input/notebook) with the fixes applied. Please add your HF token so you don't get an error, and then run all cells.
